globals:
  YEARLY_TAKE_HOME_PAY:
    "2024": 65000
    "2025": 68000
  SANKEY_OTHER_THRESHOLD: 0.03
  PROJECTED_SPENDING_BILL_THRESHOLD: 100

plots:
  bills_over_time:
    timeframe: yearly
    title: "Money spent on bills over time"
    lines:
      - filters:
        - column: Category
          operator: iequals
          value: Bills
        style: b
        label: bills
      - filters: []
        style: g
        label: total

  food_over_time:
    timeframe: yearly
    title: "Money spent on food over time"
    lines:
      - filters:
        - column: "Is Food"
          operator: "="
          value: 1
        style: b

aggregations:
  coffees_bought:
    filters:
      - column: Description
        operator: icontains
        value: coffee
    agg:
      func: count

  spent_on_coffee:
    filters:
      - column: Description
        operator: icontains
        value: coffee
    agg:
      func: sum
      column: Price

  spent_on_gas:
    filters:
      - column: Description
        operator: "="
        value: Gas
    agg:
      func: sum
      column: Price