name: Check Commit
run-name: Checking ${{ github.sha }}
on: [push]
jobs:
  check-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Install Dev Dependencies
        run: python3 -m pip install -r requirements-dev.txt
      - name: Initialize
        run: python3 main.py init < /dev/null
      - name: Check Formatting
        run: python3 -m black --check src tests main.py
      - name: Linting
        run: python3 -m flake8 src tests main.py
      - name: Type Check
        run: mypy src --config-file=mypy.ini
      - name: Tests
        run: python3 -m pytest